name: TFSec

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec.sarif     
      
      - name: GitHub Security Report Action
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ secrets.SECURITY_REPORT_BOT_TOKEN }}
          sarifReportDir: ${{ github.workspace }}
      
      - name: ls output dir
        run: ls -la ${{ github.workspace }}

      - name: Upload security report
        uses: actions/upload-artifact@v2
        with:
          name: SecuritySummary
          path: ${{ github.workspace }}/summary.pdf
